### ISSUE TITLE
IMPORT FAILED

### ISSUE THREAD

**Issue by caissonfiv** [ronniebasak/ComfyUI-Tara-LLM-Integration#1]
Traceback (most recent call last):
  File "E:\AI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1864, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Tara-LLM-Integration\__init__.py", line 7, in <module>
    from .py.tara_advanced import TaraPrompterAdvancedNode, TaraLLMConfigNode, TaraAdvancedCompositionNode, TaraPresetLLMConfigNode
  File "E:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Tara-LLM-Integration\py\tara_advanced.py", line 69
    "content": f"""Provided Positive Prompt: {prompt_positive}{f"\n\nProvided Negative Prompt: {prompt_negative}" if  prompt_negative else ""}""",

                         ^
SyntaxError: f-string expression part cannot include a backslash

Cannot import E:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Tara-LLM-Integration module for custom nodes: f-string expression part cannot include a backslash (tara_advanced.py, line 69)

**Comment by ashxtrem** [comment]
Happening same on my system too

`Traceback (most recent call last):
  File "E:\AI\ComfyUI_windows_portable_nightly_pytorch\ComfyUI\nodes.py", line 1864, in load_custom_node 
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\AI\ComfyUI_windows_portable_nightly_pytorch\ComfyUI\custom_nodes\ComfyUI-Tara-LLM-Integration\__init__.py", line 7, in <module>
    from .py.tara_advanced import TaraPrompterAdvancedNode, TaraLLMConfigNode, TaraAdvancedCompositionNode, TaraPresetLLMConfigNode
  File "E:\AI\ComfyUI_windows_portable_nightly_pytorch\ComfyUI\custom_nodes\ComfyUI-Tara-LLM-Integration\py\tara_advanced.py", line 69
    "content": f"""Provided Positive Prompt: {prompt_positive}{f"\n\nProvided Negative Prompt: {prompt_negative}" if  prompt_negative else ""}""",`
    
    Env imfo:
    `** Platform: Windows
** Python version: 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
** Python executable: E:\AI\ComfyUI_windows_portable_nightly_pytorch\python_embeded\python.exe`

**Comment by ronniebasak** [comment]
I used Python 3.12, I'll try Py 3.10, it might take a while to build with all the dependencies. I'll definitely fix this.

**Comment by ronniebasak** [comment]
Also, I tried on Linux, I'll first try Python 3.10 and then Check on windows. I have to install windows first :D

**Comment by Lumabrik** [comment]
> I used Python 3.12, I'll try Py 3.10, it might take a while to build with all the dependencies. I'll definitely fix this.

Thanks for this. A lot of us in windows use Py 3.10 as thats the one originally  recommended for Automatic 1111 / Forge / Foocus / Comfy.

**Comment by ronniebasak** [comment]
I've made a fix where i don't use f-strings anymore on this use-case. Should import fine now

**Comment by ronniebasak** [comment]
I'm closing this issue assuming the above has fixed it for anyone. Please feel free to reopen in case this issue persists.
